#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/http-auth/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-http-auth-post-app-clone-setup() {
  declare desc="clones properties and htpasswd for the new app"
  declare trigger="post-app-clone-setup"
  declare OLD_APP="$1" NEW_APP="$2"

  fn-plugin-property-clone "http-auth" "$OLD_APP" "$NEW_APP"
  if fn-http-auth-has-htpasswd "$OLD_APP"; then
    fn-http-auth-ensure-htpasswd "$OLD_APP"
    sudo "$(fn-http-auth-htpasswd-helper)" clone "$OLD_APP" "$NEW_APP"
  fi
  fn-http-auth-sync-config "$NEW_APP"
}

trigger-http-auth-post-app-clone-setup "$@"
