#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-http-auth-post-app-rename-setup() {
  declare desc="updates settings for new app"
  declare trigger="post-app-rename-setup"
  declare OLD_APP="$1" NEW_APP="$2"

  fn-plugin-property-clone "http-auth" "$OLD_APP" "$NEW_APP"
  fn-plugin-property-destroy "http-auth" "$OLD_APP"
}

trigger-http-auth-post-app-rename-setup "$@"
