#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/http-auth/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-http-auth-post-delete() {
  declare desc="destroys the http-auth properties for a given app"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "http-auth" "$APP"
  sudo "$PLUGIN_AVAILABLE_PATH/http-auth/bin/teardown-htpasswd" "$APP"
  rm -f "$DOKKU_LIB_ROOT/data/http-auth/$APP"
  rm -f "$DOKKU_ROOT/$APP/nginx.conf.d/http-auth.conf"
}

trigger-http-auth-post-delete "$@"
